#!/usr/bin/env bash
#
# Give a prebuilt Android project the Paseo Edge identity and signing config.
#
# Run this after `expo prebuild --platform android` and before Gradle. It is the
# Android counterpart of the `electron-builder -c` flags the desktop build uses:
# upstream's files stay untouched and only the generated `android/` project — which
# is throwaway, regenerated by every prebuild and gitignored — is changed.
#
# Two things move:
#
#   applicationId  sh.paseo -> sh.paseo.edge, so Edge installs beside a stock Paseo
#                  instead of colliding with it (a same-id install is refused anyway,
#                  because the signing keys differ).
#   app_name       "Paseo" -> "Paseo Edge", the launcher label.
#
# The applicationId and the release signingConfig are set by *appending* a second
# `android { }` block rather than editing the generated one. Gradle evaluates the file
# top to bottom, so the later block wins, and there is no anchor text in upstream's
# template for a prebuild to move out from under us. The two assertions below are the
# exception: they read the generated values first so a changed upstream id or app name
# fails the build loudly rather than shipping something mislabelled.
#
# Usage:
#   scripts/edge/android-identity.sh [--android-dir DIR] [--app-id ID] [--app-name NAME]
#
# The release build then needs the keystore in the environment:
#   EDGE_ANDROID_KEYSTORE           path to the keystore file
#   EDGE_ANDROID_KEYSTORE_PASSWORD  its password (PKCS12: key password is the same)
#   EDGE_ANDROID_KEY_ALIAS          optional, defaults to paseo-edge

set -euo pipefail

ANDROID_DIR="packages/app/android"
APP_ID="sh.paseo.edge"
APP_NAME="Paseo Edge"
UPSTREAM_APP_ID="sh.paseo"
UPSTREAM_APP_NAME="Paseo"
MARKER="// --- Paseo Edge ---"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --android-dir) ANDROID_DIR="$2"; shift 2 ;;
        --app-id) APP_ID="$2"; shift 2 ;;
        --app-name) APP_NAME="$2"; shift 2 ;;
        -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

gradle_file="$ANDROID_DIR/app/build.gradle"
strings_file="$ANDROID_DIR/app/src/main/res/values/strings.xml"

for f in "$gradle_file" "$strings_file"; do
    [[ -f "$f" ]] || { echo "Not a prebuilt Android project: $f is missing" >&2; exit 1; }
done

if grep -qF "$MARKER" "$gradle_file"; then
    echo "$gradle_file already carries the Edge identity — prebuild with --clean first" >&2
    exit 1
fi

# Both of these are what `expo prebuild` writes from packages/app/app.config.js. If
# either has moved, the patch below would still "succeed" and produce an APK named or
# addressed wrongly, so stop here instead.
grep -qF "applicationId '$UPSTREAM_APP_ID'" "$gradle_file" || {
    echo "Expected applicationId '$UPSTREAM_APP_ID' in $gradle_file — upstream changed it" >&2
    exit 1
}
grep -qF "<string name=\"app_name\">$UPSTREAM_APP_NAME</string>" "$strings_file" || {
    echo "Expected app_name $UPSTREAM_APP_NAME in $strings_file — upstream changed it" >&2
    exit 1
}

sed -i "s|<string name=\"app_name\">$UPSTREAM_APP_NAME</string>|<string name=\"app_name\">$APP_NAME</string>|" \
    "$strings_file"

cat >> "$gradle_file" <<GRADLE

$MARKER-------------------------------------------------------------
// Appended by scripts/edge/android-identity.sh. Reconfigures what the generated
// project above set: the last assignment wins, so nothing here depends on the shape
// of Expo's template.
def edgeKeystore = System.getenv("EDGE_ANDROID_KEYSTORE")
def edgeKeystorePassword = System.getenv("EDGE_ANDROID_KEYSTORE_PASSWORD")
def edgeKeyAlias = System.getenv("EDGE_ANDROID_KEY_ALIAS") ?: "paseo-edge"

android {
    defaultConfig {
        applicationId '$APP_ID'
    }

    // Expo's template signs release builds with the debug keystore, which every
    // Android install ships and anyone can sign with. Edge releases are public
    // artifacts, so they get their own key — and the build fails rather than quietly
    // falling back to the debug one, which would install fine and be indistinguishable
    // until someone else signed an "update" for it.
    signingConfigs {
        edge {
            if (!edgeKeystore || !edgeKeystorePassword) {
                throw new GradleException(
                    "Set EDGE_ANDROID_KEYSTORE and EDGE_ANDROID_KEYSTORE_PASSWORD to sign an Edge release build")
            }
            storeFile file(edgeKeystore)
            storePassword edgeKeystorePassword
            keyAlias edgeKeyAlias
            keyPassword edgeKeystorePassword
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.edge
        }
    }
}
GRADLE

echo "applicationId -> $APP_ID"
echo "app_name      -> $APP_NAME"
grep -n "app_name" "$strings_file"
