#!/usr/bin/env bash
#
# Install a "Paseo Edge" launcher that runs the Edge build alongside a stock Paseo.
#
# Both apps otherwise share ~/.config/Paseo, because packages/desktop/src/main.ts
# hardcodes the Electron app name. Sharing userData means sharing the single-instance
# lock, so launching Edge over a running stock Paseo focuses the stock window and
# exits, which reads as the AppImage doing nothing. The launcher gives Edge its own
# profile via PASEO_ELECTRON_USER_DATA_DIR, which upstream honours in packaged builds.
#
# Usage: scripts/edge/install-launcher.sh [/path/to/Paseo-Edge-x86_64.AppImage]

set -euo pipefail

APPIMAGE_DEFAULT="$HOME/Applications/Paseo-Edge-x86_64.AppImage"
appimage="${1:-$APPIMAGE_DEFAULT}"

repo_root="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"

bin_dir="$HOME/.local/bin"
launcher="$bin_dir/paseo-edge"
desktop_dir="$HOME/.local/share/applications"
desktop_entry="$desktop_dir/paseo-edge.desktop"
icon_root="$HOME/.local/share/icons/hicolor"

mkdir -p "$bin_dir" "$desktop_dir" "$(dirname "$appimage")"

# Edge takes the dev-build icon: a blue blueprint version of the same mark, already
# in the repo for unpackaged runs (packages/desktop/src/main.ts:573). Stock Paseo's is
# black, so the two are told apart in a launcher or taskbar without editing an image.
icon_src="$repo_root/packages/desktop/assets/icon-dev.png"
if [[ -f "$icon_src" ]]; then
  if command -v magick > /dev/null; then
    for size in 512 256 128 64 48; do
      mkdir -p "$icon_root/${size}x${size}/apps"
      magick "$icon_src" -resize "${size}x${size}" "$icon_root/${size}x${size}/apps/paseo-edge.png"
    done
  else
    mkdir -p "$icon_root/512x512/apps"
    cp "$icon_src" "$icon_root/512x512/apps/paseo-edge.png"
  fi
  if command -v gtk-update-icon-cache > /dev/null && [[ -f "$icon_root/index.theme" ]]; then
    gtk-update-icon-cache -q -t "$icon_root" || true
  fi
  icon_installed=true
else
  echo "warning: $icon_src not found; the launcher entry will have no icon." >&2
  icon_installed=false
fi

cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by scripts/edge/install-launcher.sh — edit there, not here.
set -euo pipefail

APPIMAGE="\${PASEO_EDGE_APPIMAGE:-$appimage}"
PROFILE="\${PASEO_EDGE_PROFILE:-\$HOME/.config/Paseo-Edge}"
STOCK_SETTINGS="\$HOME/.config/Paseo/desktop-settings.json"
EDGE_SETTINGS="\$PROFILE/desktop-settings.json"

if [[ ! -x "\$APPIMAGE" ]]; then
  echo "Paseo Edge AppImage not found or not executable: \$APPIMAGE" >&2
  echo "Download it from https://github.com/josham/paseo/releases and chmod +x it," >&2
  echo "or set PASEO_EDGE_APPIMAGE to its path." >&2
  exit 1
fi

mkdir -p "\$PROFILE"

# Seed the profile once. A fresh profile would otherwise take
# DEFAULT_DESKTOP_SETTINGS.daemon.manageBuiltInDaemon = true and try to manage its
# own daemon next to the one already running, leaving two daemons over ~/.paseo.
# Edge is a second client here, never a daemon owner, so that stays false whatever
# the stock app is set to.
if [[ ! -f "\$EDGE_SETTINGS" ]]; then
  if [[ -f "\$STOCK_SETTINGS" ]]; then
    python3 - "\$STOCK_SETTINGS" "\$EDGE_SETTINGS" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
data = json.load(open(src))
data.setdefault("settings", {}).setdefault("daemon", {})["manageBuiltInDaemon"] = False
json.dump(data, open(dst, "w"), indent=2)
PY
  else
    cat > "\$EDGE_SETTINGS" <<'SETTINGS'
{
  "version": 1,
  "settings": {
    "daemon": {
      "manageBuiltInDaemon": false,
      "keepRunningAfterQuit": false
    }
  }
}
SETTINGS
  fi
  echo "seeded \$EDGE_SETTINGS (attaches to the running daemon, never manages one)"
fi

exec env \\
  PASEO_ELECTRON_USER_DATA_DIR="\$PROFILE" \\
  PASEO_TEST_APP_NAME="Paseo Edge" \\
  "\$APPIMAGE" "\$@"
LAUNCHER
chmod +x "$launcher"

cat > "$desktop_entry" <<ENTRY
[Desktop Entry]
Name=Paseo Edge
Comment=Paseo Edge — fork build, runs alongside a stock Paseo
Exec=$launcher %U
Icon=paseo-edge
Terminal=false
Type=Application
Categories=Development;
StartupWMClass=Paseo Edge
ENTRY

echo "installed:"
echo "  $launcher"
echo "  $desktop_entry"
if [[ "$icon_installed" == true ]]; then
  echo "  $icon_root/*/apps/paseo-edge.png"
fi
echo
echo "AppImage expected at: $appimage"
if [[ ! -x "$appimage" ]]; then
  echo "  (not there yet — download it from the releases page and chmod +x)"
fi
echo
echo "Run 'paseo-edge' if ~/.local/bin is on PATH, or pick \"Paseo Edge\" from your launcher."
