#!/usr/bin/env bash
#
# Install the Paseo Edge daemon from a release, with no checkout and no build.
#
# Edge ships the daemon twice over: inside the app, and as npm tarballs attached to
# the same release. This installs the tarballs into their own prefix so a service can
# run the daemon as plain Node — no Electron, no browser process — while staying on
# exactly the commit the installed AppImage came from.
#
# The daemon and the app both report upstream's version (Settings -> About compares
# them, so the daemon must keep upstream's number), which means the package version
# cannot tell two Edge builds apart. The release tag is the key instead: it is written
# to $PREFIX/EDGE_TAG here so a sync can compare it against the app.
#
# Usage:
#   scripts/edge/install-daemon.sh [edge-vX.Y.Z] [--prefix DIR] [--restart]
#   scripts/edge/install-daemon.sh --bundle paseo-edge-daemon-X.Y.Z.tar.gz
#
# With no tag, installs the newest edge-v* release. --bundle installs a bundle already
# on disk and takes its tag from the archive, which is also how to install offline.

set -euo pipefail

REPO="${PASEO_EDGE_REPO:-josham/paseo}"
PREFIX="${PASEO_EDGE_DAEMON_PREFIX:-$HOME/.local/share/paseo-edge-daemon}"
LAUNCHER="${PASEO_EDGE_DAEMON_LAUNCHER:-$HOME/.local/bin/paseo-edge-daemon}"
tag=""
bundle=""
restart=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix) PREFIX="$2"; shift 2 ;;
        --bundle) bundle="$2"; shift 2 ;;
        --restart) restart=1; shift ;;
        -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        edge-v*) tag="$1"; shift ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

for tool in curl tar npm node; do
    command -v "$tool" >/dev/null 2>&1 || { echo "Required tool missing: $tool" >&2; exit 1; }
done

api() { curl -fsSL -H 'Accept: application/vnd.github+json' ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} "$@"; }

if [[ -z "$tag" && -z "$bundle" ]]; then
    # Not /releases/latest: the fork inherited every upstream tag, so pick the newest
    # release whose tag is actually ours.
    tag="$(api "https://api.github.com/repos/$REPO/releases?per_page=50" |
        node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
            const r=JSON.parse(s).filter(x=>!x.draft&&/^edge-v/.test(x.tag_name));
            if(!r.length){console.error("No edge-v* release found");process.exit(1)}
            console.log(r[0].tag_name);})')"
fi
version="${tag#edge-v}"
asset="paseo-edge-daemon-${version}.tar.gz"

echo "Installing the Paseo Edge daemon"
echo "  release : $tag"
echo "  prefix  : $PREFIX"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

if [[ -n "$bundle" ]]; then
    echo "  bundle  : $bundle (local)"
    tar xzf "$bundle" -C "$work"
    # A local bundle carries its own tag, so trust that over anything guessed above.
    [[ -f "$work/EDGE_TAG" ]] && tag="$(cat "$work/EDGE_TAG")"
else
    url="https://github.com/$REPO/releases/download/$tag/$asset"
    echo "  fetching: $url"
    curl -fsSL --retry 3 -o "$work/$asset" "$url" || {
        echo "Could not download $asset from $tag." >&2
        echo "Releases before the daemon bundle was introduced do not carry one." >&2
        exit 1
    }
    tar xzf "$work/$asset" -C "$work"
fi

packs=("$work"/*.tgz)
if (( ${#packs[@]} == 0 )); then
    echo "Bundle contained no package tarballs" >&2
    exit 1
fi

# All seven in one install so they resolve each other from the bundle rather than
# from the registry. npm still fetches third-party dependencies, so this needs
# network; the tarballs are only Paseo's own packages.
mkdir -p "$PREFIX"
npm install --prefix "$PREFIX" "${packs[@]}"

paseo_bin="$PREFIX/node_modules/.bin/paseo"
[[ -x "$paseo_bin" ]] || { echo "Install finished but $paseo_bin is missing" >&2; exit 1; }
printf '%s\n' "$tag" > "$PREFIX/EDGE_TAG"

mkdir -p "$(dirname "$LAUNCHER")"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Generated by scripts/edge/install-daemon.sh — rerun that, do not edit this.
# Installed from $tag.
exec "$paseo_bin" "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

echo
echo "Installed $("$paseo_bin" --version 2>/dev/null || echo "unknown version") from $tag"
echo "  daemon  : $paseo_bin"
echo "  launcher: $LAUNCHER"

if (( restart )); then
    echo "Restarting paseo-daemon (this stops any agent running on it)…"
    systemctl --user restart paseo-daemon
else
    echo
    echo "Point the service at it and restart when no agent is mid-run:"
    echo "  ExecStart=$LAUNCHER daemon start --foreground"
    echo "  systemctl --user restart paseo-daemon"
fi
